name: Check Build

on:
  pull_request:
    branches: [ master ]

jobs:
  jsBuild:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}_jsBuild
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: KMP cache
        uses: actions/cache@v2
        id: konan-js-build
        with:
          path: '~/.konan/**'
          key: konan-js-build
      - name: Compile Javascript app
        run: set -o pipefail && bash ./deploy/build.sh functions
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Javascript build
          path: |
            functions/*.js
            functions/*.json