name: Check Build

on:
  pull_request:
    branches: [ master ]

env:
  JAVA_VERSION: "15"

jobs:
  jsBuild:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}_jsBuild
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: KMP cache
        uses: actions/cache@v2
        id: konan-js-build
        with:
          path: '~/.konan/**'
          key: konan-js-build
      - name: Compile Javascript app
        run: set -o pipefail && bash ./scripts/build.sh
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Javascript build
          path: |
            build/production/*.json
            build/production/*.ts
            build/production/*.map

  jsTest:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}_jsTest
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: KMP cache
        uses: actions/cache@v2
        id: konan-js-test
        with:
          path: '~/.konan/**'
          key: konan-js-test
      - name: Javascript tests
        run: set -o pipefail && ./gradlew --continue nodeTest
      # Always run this job even if the previous steps fail to collect all test reports
      - name: Generate Javascript test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: 'jsTestResults'
      # Always run this job even if the previous steps fail to collect all artifacts
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Javascript test results
          path: '**/build/test-results/**/TEST-*.xml'