name: Deploy Build

on:
  push:
    branches: [ master ]

jobs:
  jsDeploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.ref }}_jsDeploy
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: KMP cache
        uses: actions/cache@v2
        id: konan-js-deploy
        with:
          path: '~/.konan/**'
          key: konan-js-deploy
      - name: Compile Javascript app
        run: set -o pipefail && bash ./deploy/build.sh functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Javascript deploy
          path: |
            functions/index/**
            functions/index.js
            functions/index.js.map
            functions/index.meta.js
            functions/package.json
            functions/package-lock.json
            firebase-debug.log*
            firebase-debug.*.log